POST http://localhost:3000/register
Content-Type: application/json

{
    "full_name": "Tom Henry",
    "email": "tomys@email.com",
    "password": "secret123"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "tomys@email.com",
    "password": "secret123"
}
###
POST http://localhost:3000/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTY0NzQzMDA5NiwiZXhwIjoxNjQ3NTE2NDk2fQ.HboJbOp3lgHhO-NYXXupMIYkjH7bJhv9aLEe6ZBzLpI

###
GET http://localhost:3000/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNjQ3NDI3Mzg4LCJleHAiOjE2NDc1MTM3ODh9.Ci8wS0OsbMlYq-rIzUKfgiL6Z9zFFH79HbDJynOuf78
###
GET http://localhost:3000/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTY0NzQzMDA5NiwiZXhwIjoxNjQ3NTE2NDk2fQ.HboJbOp3lgHhO-NYXXupMIYkjH7bJhv9aLEe6ZBzLpI
###
GET http://localhost:3000/bills/2