POST http://localhost:3000/register
Content-Type: application/json

{
    "full_name": "Tom Henry",
    "email": "tomys@email.com",
    "password": "secret123"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "tomys@email.com",
    "password": "secret123"
}